import { z } from "zod";

export const UserSchema = z.object({
  id: z.string().uuid().optional(), // Generated by DB
  name: z.string(),
  email: z.string().email(),
  password: z.string(),
  isActive: z.boolean().default(true),
  createdAt: z.string().datetime().optional(), // Standard naming
  updatedAt: z.string().datetime().optional(),
});

export type User = z.infer<typeof UserSchema>;